name: Build Windows App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Generate Windows Runner
        run: |
          mv lib/main.dart lib/main_backup.dart
          flutter create --platforms windows --org com.unad.planner --project-name unad_planner .
          rm lib/main.dart
          mv lib/main_backup.dart lib/main.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnadPlanner-Windows
          path: build/windows/x64/runner/Release/
